---
- hosts: webservers
- name: Webserver assignment
  import_playbook: ../static-assignments/webservers.yml

- hosts: lb
- name: Loadbalancers assignment
  import_playbook: ../static-assignments/loadbalancers.yml
  when: load_balancer_is_required