---
- hosts: uat-webservers
- name: uat-webservers assignment
  import_playbook: ../static-assignments/uat-webservers.yml

- hosts: lb
- name: Loadbalancers assignment
  import_playbook: ../static-assignments/loadbalancers.yml
  when: load_balancer_is_required